version: 2.1

# Define reusable commands
commands:
  setup_python_env:
    description: "Set up Python environment with dependencies"
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip python3-venv
      - run:
          name: Create virtual environment
          command: |
            python3 -m venv .venv
            echo 'export PATH=.venv/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            source .venv/bin/activate
            pip install --upgrade pip
            pip install torch torchvision numpy matplotlib tqdm
            pip install flake8 black isort pytest pytest-cov

# Define jobs
jobs:
  lint:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/mnist-training
    steps:
      - setup_python_env
      - run:
          name: Run code formatting check (black)
          command: |
            source .venv/bin/activate
            black --check --diff src/ tests/
      - run:
          name: Run import sorting check (isort)
          command: |
            source .venv/bin/activate
            isort --check-only --diff src/ tests/
      - run:
          name: Run flake8 linting
          command: |
            source .venv/bin/activate
            flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503

  test:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/mnist-training
    steps:
      - setup_python_env
      - run:
          name: Create test data directory
          command: mkdir -p test_data
      - run:
          name: Run test_train.py
          command: |
            source .venv/bin/activate
            PYTHONPATH=src python tests/test_train.py
      - run:
          name: Run test_utils.py
          command: |
            source .venv/bin/activate
            PYTHONPATH=src python tests/test_utils.py
      - run:
          name: Run test_transforms.py
          command: |
            source .venv/bin/activate
            PYTHONPATH=src python tests/test_transforms.py
      - run:
          name: Run all tests with pytest
          command: |
            source .venv/bin/activate
            PYTHONPATH=src pytest tests/ -v --tb=short
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

# Define workflows
workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
      - test

  # Optional: Nightly full test (can be enabled if needed)
  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 2 * * *"  # Run at 2 AM daily
  #         filters:
  #           branches:
  #             only:
  #               - main
  #   jobs:
  #     - lint
  #     - test 